### PR TITLE
fix: proper dir structure in ~/.robin

### LINKED ISSUE #43: Robin logs should not live in the same folder as the channel installation
beta logs currently live in `~/.robin/beta/logs.db`, but should instead live in `~/.robin/logs/robin-beta.db`.

### PR DESCRIPTION
**Pull request by karimsa**
Fixes #43.

Directory contents before:

Screenshot 2023-03-05 at 3 28 29 PM

Contents after:

Screenshot 2023-03-05 at 3 27 48 PM

### CODE REVIEW

File: backend/internal/upgrade/upgrade.go [hunk 1]
```diff
@@ -178,12 +183,20 @@ func UpgradeChannel(releaseChannel config.ReleaseChannel) (string, string, error
 		upgradeExecName += ".exe"
 	}
 
-	if err := os.Symlink(filepath.Join(channelDir, "bin", "robin"), filepath.Join(config.GetRobinPath(), "bin", linkExecName)); err != nil && !os.IsExist(err) {
+	// delete and recreate symlink
```
Comment (karimsa) [inline backend/internal/upgrade/upgrade.go:186]: delete + symlink is almost as fast as symlink (one tiny syscall to delete is not slow obviously) - but this way you end up with accurate links at the end of it

File: backend/internal/process/process.go [hunk 2]
```diff
@@ -265,11 +272,18 @@ func (m *ProcessManager[Meta]) Spawn(procConfig ProcessConfig[Meta]) (*Process[M
 		Meta:      procConfig.Meta,
 	}
 
+	// Reap zombies
+	go entry.waitForExit(entry.Pid)
```
Comment (karimsa) [inline backend/internal/process/process.go:276]: It is important to start the reaper immediately, because if anything fails, we want to be reaping still
